In [5]:
import pandas as pd
import os
# Read customer data from CSV file into DataFrame
customers_df = pd.read_csv(r'D:\Datamamagemet\python\source\bikestore_dim\staging_1\customers\customers.csv')

# Read store data from CSV file into DataFrame
store_df = pd.read_csv(r'D:\Datamamagemet\python\source\bikestore_dim\staging_1\store\store.csv')

# Display the store DataFrame
store_df

,store_id,store_name,phone,email,street,city,state,zip_code,extract_time,source
0,1,Santa Cruz Bikes,(831) 476-4321,Not available,3700 Portola Drive,Santa Cruz,CA,0.0,1.714325e+09,datalake
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432.0,1.714325e+09,datalake
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088.0,1.714325e+09,datalake

In [7]:
store_city = list(store_df['city'])
store_city

['Santa Cruz', 'Baldwin', 'Rowlett']

In [13]:
# Add a new column 'local' to customers_df indicating if the customer's city is in store_city list
customers_df['local'] = customers_df['city'].isin(store_city)

In [14]:
customers_df

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,extract_time,source,local
0,1,Debra,Burks,Not available,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,1.714319e+09,csv,False
1,2,Kasha,Todd,Not available,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,1.714319e+09,csv,False
2,3,Tameka,Fisher,Not available,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,1.714319e+09,csv,False
3,4,Daryl,Spence,Not available,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,1.714319e+09,csv,False
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,1.714319e+09,csv,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,Not available,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301,1.714319e+09,csv,False
1441,1442,Cassie,Cline,Not available,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201,1.714319e+09,csv,False
1442,1443,Lezlie,Lamb,Not available,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722,1.714319e+09,csv,False
1443,1444,Ivette,Estes,Not available,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424,1.714319e+09,csv,False
1444,1445,Ester,Acevedo,Not available,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580,1.714319e+09,csv,False

In [ ]:
# Define the output directory path for storing the processed customer data
output_dir = r'D:\Datamamagemet\python\source\bikestore_dim\staging_2\customers'

# Ensure the output directory exists, creating it if it doesn't
os.makedirs(output_dir, exist_ok=True)

# Write the processed customer data DataFrame to a CSV file in the output directory
customers_df.to_csv(os.path.join(output_dir, 'customers.csv'), index=False)